// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AudioProcessingRun struct {
	ID            int64          `json:"id"`
	StartedAt     string         `json:"started_at"`
	CompletedAt   sql.NullString `json:"completed_at"`
	Status        string         `json:"status"`
	JobsClaimed   int64          `json:"jobs_claimed"`
	JobsCompleted int64          `json:"jobs_completed"`
	JobsFailed    int64          `json:"jobs_failed"`
}

type NavidromeSync struct {
	ID              int64          `json:"id"`
	StartedAt       string         `json:"started_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	TracksProcessed int64          `json:"tracks_processed"`
	TracksUpdated   int64          `json:"tracks_updated"`
	TracksDeleted   int64          `json:"tracks_deleted"`
	Status          string         `json:"status"`
	CreatedAt       string         `json:"created_at"`
}

type NavidromeTrackSyncStatus struct {
	TrackID      int64  `json:"track_id"`
	NavidromeID  string `json:"navidrome_id"`
	LastSyncedAt string `json:"last_synced_at"`
	SyncID       int64  `json:"sync_id"`
	CreatedAt    string `json:"created_at"`
}

type Track struct {
	ID              int64          `json:"id"`
	NavidromeID     string         `json:"navidrome_id"`
	Title           string         `json:"title"`
	Artist          string         `json:"artist"`
	ArtistID        sql.NullString `json:"artist_id"`
	Album           string         `json:"album"`
	AlbumID         sql.NullString `json:"album_id"`
	AlbumArtist     sql.NullString `json:"album_artist"`
	Genre           sql.NullString `json:"genre"`
	Year            sql.NullInt64  `json:"year"`
	TrackNumber     sql.NullInt64  `json:"track_number"`
	DiscNumber      sql.NullInt64  `json:"disc_number"`
	DurationSeconds int64          `json:"duration_seconds"`
	Bitrate         sql.NullInt64  `json:"bitrate"`
	FileSize        sql.NullInt64  `json:"file_size"`
	Path            string         `json:"path"`
	ContentType     sql.NullString `json:"content_type"`
	Suffix          string         `json:"suffix"`
	CreatedAt       string         `json:"created_at"`
}

type TrackAudioAnalysis struct {
	ID            int64          `json:"id"`
	TrackID       int64          `json:"track_id"`
	Status        string         `json:"status"`
	ProcessedAt   sql.NullString `json:"processed_at"`
	Error         sql.NullString `json:"error"`
	Attempts      int64          `json:"attempts"`
	LastAttemptAt sql.NullString `json:"last_attempt_at"`
	CreatedAt     string         `json:"created_at"`
	ClaimedAt     sql.NullString `json:"claimed_at"`
	ClaimedBy     sql.NullString `json:"claimed_by"`
}

type TrackAudioFeature struct {
	TrackID                int64           `json:"track_id"`
	AnalyzedAt             string          `json:"analyzed_at"`
	FileDurationSeconds    float64         `json:"file_duration_seconds"`
	MeasuredIntegratedLufs sql.NullFloat64 `json:"measured_integrated_lufs"`
	MeasuredTruePeak       sql.NullFloat64 `json:"measured_true_peak"`
	ReplaygainTrackGainDb  sql.NullFloat64 `json:"replaygain_track_gain_db"`
	ReplaygainTrackPeak    sql.NullFloat64 `json:"replaygain_track_peak"`
	ReplaygainAlbumGainDb  sql.NullFloat64 `json:"replaygain_album_gain_db"`
	ReplaygainAlbumPeak    sql.NullFloat64 `json:"replaygain_album_peak"`
	EffectiveGainDb        sql.NullFloat64 `json:"effective_gain_db"`
	EffectivePeak          sql.NullFloat64 `json:"effective_peak"`
	EffectiveGainSource    string          `json:"effective_gain_source"`
	EffectivePeakSource    string          `json:"effective_peak_source"`
}

type TrackEmbeddingJob struct {
	ID            int64          `json:"id"`
	TrackID       int64          `json:"track_id"`
	Status        string         `json:"status"`
	ProcessedAt   sql.NullString `json:"processed_at"`
	Error         sql.NullString `json:"error"`
	Attempts      int64          `json:"attempts"`
	LastAttemptAt sql.NullString `json:"last_attempt_at"`
	CreatedAt     string         `json:"created_at"`
	ClaimedAt     sql.NullString `json:"claimed_at"`
	ClaimedBy     sql.NullString `json:"claimed_by"`
}
