// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: syncs.sql

package db

import (
	"context"
	"database/sql"
)

const completeSync = `-- name: CompleteSync :exec
UPDATE navidrome_syncs
SET completed_at = ?, status = ?, tracks_processed = ?, tracks_updated = ?
WHERE id = ?
`

type CompleteSyncParams struct {
	CompletedAt     sql.NullString `json:"completed_at"`
	Status          string         `json:"status"`
	TracksProcessed int64          `json:"tracks_processed"`
	TracksUpdated   int64          `json:"tracks_updated"`
	ID              int64          `json:"id"`
}

func (q *Queries) CompleteSync(ctx context.Context, arg CompleteSyncParams) error {
	_, err := q.db.ExecContext(ctx, completeSync,
		arg.CompletedAt,
		arg.Status,
		arg.TracksProcessed,
		arg.TracksUpdated,
		arg.ID,
	)
	return err
}

const createSync = `-- name: CreateSync :one
INSERT INTO navidrome_syncs (started_at, status)
VALUES (?, 'in_progress')
RETURNING id
`

func (q *Queries) CreateSync(ctx context.Context, startedAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSync, startedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}
