// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const claimPendingAudioJobs = `-- name: ClaimPendingAudioJobs :many
UPDATE track_audio_analysis
SET status = 'processing',
    claimed_at = ?,
    claimed_by = ?,
    error = NULL
WHERE id IN (
  SELECT id
  FROM track_audio_analysis
  WHERE track_audio_analysis.status = 'pending'
     OR (
       track_audio_analysis.status = 'processing'
       AND track_audio_analysis.claimed_at IS NOT NULL
       AND track_audio_analysis.claimed_at <= ?
     )
  ORDER BY track_audio_analysis.created_at, track_audio_analysis.id
  LIMIT ?
)
RETURNING id, track_id
`

type ClaimPendingAudioJobsParams struct {
	ClaimedAt   sql.NullString `json:"claimed_at"`
	ClaimedBy   sql.NullString `json:"claimed_by"`
	ClaimedAt_2 sql.NullString `json:"claimed_at_2"`
	Limit       int64          `json:"limit"`
}

type ClaimPendingAudioJobsRow struct {
	ID      int64 `json:"id"`
	TrackID int64 `json:"track_id"`
}

func (q *Queries) ClaimPendingAudioJobs(ctx context.Context, arg ClaimPendingAudioJobsParams) ([]ClaimPendingAudioJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, claimPendingAudioJobs,
		arg.ClaimedAt,
		arg.ClaimedBy,
		arg.ClaimedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingAudioJobsRow
	for rows.Next() {
		var i ClaimPendingAudioJobsRow
		if err := rows.Scan(&i.ID, &i.TrackID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeAudioProcessingRun = `-- name: CompleteAudioProcessingRun :exec
UPDATE audio_processing_runs
SET completed_at = ?, status = ?, jobs_claimed = ?, jobs_completed = ?, jobs_failed = ?
WHERE id = ?
`

type CompleteAudioProcessingRunParams struct {
	CompletedAt   sql.NullString `json:"completed_at"`
	Status        string         `json:"status"`
	JobsClaimed   int64          `json:"jobs_claimed"`
	JobsCompleted int64          `json:"jobs_completed"`
	JobsFailed    int64          `json:"jobs_failed"`
	ID            int64          `json:"id"`
}

func (q *Queries) CompleteAudioProcessingRun(ctx context.Context, arg CompleteAudioProcessingRunParams) error {
	_, err := q.db.ExecContext(ctx, completeAudioProcessingRun,
		arg.CompletedAt,
		arg.Status,
		arg.JobsClaimed,
		arg.JobsCompleted,
		arg.JobsFailed,
		arg.ID,
	)
	return err
}

const createAudioProcessingRun = `-- name: CreateAudioProcessingRun :one
INSERT INTO audio_processing_runs (started_at, status)
VALUES (?, 'in_progress')
RETURNING id
`

func (q *Queries) CreateAudioProcessingRun(ctx context.Context, startedAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAudioProcessingRun, startedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTracksByNavidromeIDs = `-- name: DeleteTracksByNavidromeIDs :exec
DELETE FROM tracks
WHERE navidrome_id IN (/*SLICE:nav_ids*/?)
`

func (q *Queries) DeleteTracksByNavidromeIDs(ctx context.Context, navIds []string) error {
	query := deleteTracksByNavidromeIDs
	var queryParams []interface{}
	if len(navIds) > 0 {
		for _, v := range navIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:nav_ids*/?", strings.Repeat(",?", len(navIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:nav_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const ensureTrackAudioJob = `-- name: EnsureTrackAudioJob :exec
INSERT INTO track_audio_analysis (
  track_id,
  status,
  processed_at,
  error,
  attempts,
  last_attempt_at,
  claimed_at,
  claimed_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(track_id) WHERE status IN ('pending', 'processing') DO UPDATE SET
  status = CASE
    WHEN track_audio_analysis.status = 'processing' THEN 'processing'
    ELSE 'pending'
  END,
  processed_at = CASE
    WHEN track_audio_analysis.status = 'processing' THEN track_audio_analysis.processed_at
    ELSE excluded.processed_at
  END,
  error = CASE
    WHEN track_audio_analysis.status = 'processing' THEN track_audio_analysis.error
    ELSE excluded.error
  END,
  attempts = CASE
    WHEN track_audio_analysis.status = 'processing' THEN track_audio_analysis.attempts
    ELSE excluded.attempts
  END,
  last_attempt_at = CASE
    WHEN track_audio_analysis.status = 'processing' THEN track_audio_analysis.last_attempt_at
    ELSE excluded.last_attempt_at
  END,
  claimed_at = CASE
    WHEN track_audio_analysis.status = 'processing' THEN track_audio_analysis.claimed_at
    ELSE excluded.claimed_at
  END,
  claimed_by = CASE
    WHEN track_audio_analysis.status = 'processing' THEN track_audio_analysis.claimed_by
    ELSE excluded.claimed_by
  END
`

type EnsureTrackAudioJobParams struct {
	TrackID       int64          `json:"track_id"`
	Status        string         `json:"status"`
	ProcessedAt   sql.NullString `json:"processed_at"`
	Error         sql.NullString `json:"error"`
	Attempts      int64          `json:"attempts"`
	LastAttemptAt sql.NullString `json:"last_attempt_at"`
	ClaimedAt     sql.NullString `json:"claimed_at"`
	ClaimedBy     sql.NullString `json:"claimed_by"`
}

func (q *Queries) EnsureTrackAudioJob(ctx context.Context, arg EnsureTrackAudioJobParams) error {
	_, err := q.db.ExecContext(ctx, ensureTrackAudioJob,
		arg.TrackID,
		arg.Status,
		arg.ProcessedAt,
		arg.Error,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.ClaimedAt,
		arg.ClaimedBy,
	)
	return err
}

const ensureTrackEmbeddingJob = `-- name: EnsureTrackEmbeddingJob :exec
INSERT INTO track_embedding_jobs (
  track_id,
  status,
  processed_at,
  error,
  attempts,
  last_attempt_at,
  claimed_at,
  claimed_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(track_id) WHERE status IN ('pending', 'processing') DO UPDATE SET
  status = CASE
    WHEN track_embedding_jobs.status = 'processing' THEN 'processing'
    ELSE 'pending'
  END,
  processed_at = CASE
    WHEN track_embedding_jobs.status = 'processing' THEN track_embedding_jobs.processed_at
    ELSE excluded.processed_at
  END,
  error = CASE
    WHEN track_embedding_jobs.status = 'processing' THEN track_embedding_jobs.error
    ELSE excluded.error
  END,
  attempts = CASE
    WHEN track_embedding_jobs.status = 'processing' THEN track_embedding_jobs.attempts
    ELSE excluded.attempts
  END,
  last_attempt_at = CASE
    WHEN track_embedding_jobs.status = 'processing' THEN track_embedding_jobs.last_attempt_at
    ELSE excluded.last_attempt_at
  END,
  claimed_at = CASE
    WHEN track_embedding_jobs.status = 'processing' THEN track_embedding_jobs.claimed_at
    ELSE excluded.claimed_at
  END,
  claimed_by = CASE
    WHEN track_embedding_jobs.status = 'processing' THEN track_embedding_jobs.claimed_by
    ELSE excluded.claimed_by
  END
`

type EnsureTrackEmbeddingJobParams struct {
	TrackID       int64          `json:"track_id"`
	Status        string         `json:"status"`
	ProcessedAt   sql.NullString `json:"processed_at"`
	Error         sql.NullString `json:"error"`
	Attempts      int64          `json:"attempts"`
	LastAttemptAt sql.NullString `json:"last_attempt_at"`
	ClaimedAt     sql.NullString `json:"claimed_at"`
	ClaimedBy     sql.NullString `json:"claimed_by"`
}

func (q *Queries) EnsureTrackEmbeddingJob(ctx context.Context, arg EnsureTrackEmbeddingJobParams) error {
	_, err := q.db.ExecContext(ctx, ensureTrackEmbeddingJob,
		arg.TrackID,
		arg.Status,
		arg.ProcessedAt,
		arg.Error,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.ClaimedAt,
		arg.ClaimedBy,
	)
	return err
}

const listAudioJobsByIDs = `-- name: ListAudioJobsByIDs :many
SELECT
  track_audio_analysis.id AS job_id,
  tracks.id, tracks.navidrome_id, tracks.title, tracks.artist, tracks.artist_id, tracks.album, tracks.album_id, tracks.album_artist, tracks.genre, tracks.year, tracks.track_number, tracks.disc_number, tracks.duration_seconds, tracks.bitrate, tracks.file_size, tracks.path, tracks.content_type, tracks.suffix, tracks.created_at
FROM track_audio_analysis
JOIN tracks ON tracks.id = track_audio_analysis.track_id
WHERE track_audio_analysis.id IN (/*SLICE:job_ids*/?)
ORDER BY track_audio_analysis.id
`

type ListAudioJobsByIDsRow struct {
	JobID int64 `json:"job_id"`
	Track Track `json:"track"`
}

func (q *Queries) ListAudioJobsByIDs(ctx context.Context, jobIds []int64) ([]ListAudioJobsByIDsRow, error) {
	query := listAudioJobsByIDs
	var queryParams []interface{}
	if len(jobIds) > 0 {
		for _, v := range jobIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:job_ids*/?", strings.Repeat(",?", len(jobIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:job_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAudioJobsByIDsRow
	for rows.Next() {
		var i ListAudioJobsByIDsRow
		if err := rows.Scan(
			&i.JobID,
			&i.Track.ID,
			&i.Track.NavidromeID,
			&i.Track.Title,
			&i.Track.Artist,
			&i.Track.ArtistID,
			&i.Track.Album,
			&i.Track.AlbumID,
			&i.Track.AlbumArtist,
			&i.Track.Genre,
			&i.Track.Year,
			&i.Track.TrackNumber,
			&i.Track.DiscNumber,
			&i.Track.DurationSeconds,
			&i.Track.Bitrate,
			&i.Track.FileSize,
			&i.Track.Path,
			&i.Track.ContentType,
			&i.Track.Suffix,
			&i.Track.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAudioJobs = `-- name: ListPendingAudioJobs :many
SELECT
  track_audio_analysis.id AS job_id,
  tracks.id, tracks.navidrome_id, tracks.title, tracks.artist, tracks.artist_id, tracks.album, tracks.album_id, tracks.album_artist, tracks.genre, tracks.year, tracks.track_number, tracks.disc_number, tracks.duration_seconds, tracks.bitrate, tracks.file_size, tracks.path, tracks.content_type, tracks.suffix, tracks.created_at
FROM track_audio_analysis
JOIN tracks ON tracks.id = track_audio_analysis.track_id
WHERE track_audio_analysis.status = 'pending'
ORDER BY track_audio_analysis.created_at, track_audio_analysis.id
LIMIT ?
`

type ListPendingAudioJobsRow struct {
	JobID int64 `json:"job_id"`
	Track Track `json:"track"`
}

func (q *Queries) ListPendingAudioJobs(ctx context.Context, limit int64) ([]ListPendingAudioJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAudioJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingAudioJobsRow
	for rows.Next() {
		var i ListPendingAudioJobsRow
		if err := rows.Scan(
			&i.JobID,
			&i.Track.ID,
			&i.Track.NavidromeID,
			&i.Track.Title,
			&i.Track.Artist,
			&i.Track.ArtistID,
			&i.Track.Album,
			&i.Track.AlbumID,
			&i.Track.AlbumArtist,
			&i.Track.Genre,
			&i.Track.Year,
			&i.Track.TrackNumber,
			&i.Track.DiscNumber,
			&i.Track.DurationSeconds,
			&i.Track.Bitrate,
			&i.Track.FileSize,
			&i.Track.Path,
			&i.Track.ContentType,
			&i.Track.Suffix,
			&i.Track.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackSyncStatus = `-- name: ListTrackSyncStatus :many
SELECT track_id, navidrome_id, last_synced_at FROM navidrome_track_sync_status
`

type ListTrackSyncStatusRow struct {
	TrackID      int64  `json:"track_id"`
	NavidromeID  string `json:"navidrome_id"`
	LastSyncedAt string `json:"last_synced_at"`
}

func (q *Queries) ListTrackSyncStatus(ctx context.Context) ([]ListTrackSyncStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackSyncStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackSyncStatusRow
	for rows.Next() {
		var i ListTrackSyncStatusRow
		if err := rows.Scan(&i.TrackID, &i.NavidromeID, &i.LastSyncedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTrackID = `-- name: SelectTrackID :one
SELECT id FROM tracks WHERE navidrome_id = ?
`

func (q *Queries) SelectTrackID(ctx context.Context, navidromeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectTrackID, navidromeID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateAudioJobStatus = `-- name: UpdateAudioJobStatus :exec
UPDATE track_audio_analysis
SET status = ?,
    processed_at = ?,
    error = ?,
    attempts = attempts + 1,
    last_attempt_at = ?,
    claimed_at = ?,
    claimed_by = ?
WHERE id = ?
`

type UpdateAudioJobStatusParams struct {
	Status        string         `json:"status"`
	ProcessedAt   sql.NullString `json:"processed_at"`
	Error         sql.NullString `json:"error"`
	LastAttemptAt sql.NullString `json:"last_attempt_at"`
	ClaimedAt     sql.NullString `json:"claimed_at"`
	ClaimedBy     sql.NullString `json:"claimed_by"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateAudioJobStatus(ctx context.Context, arg UpdateAudioJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAudioJobStatus,
		arg.Status,
		arg.ProcessedAt,
		arg.Error,
		arg.LastAttemptAt,
		arg.ClaimedAt,
		arg.ClaimedBy,
		arg.ID,
	)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (
  navidrome_id,
  title,
  artist,
  artist_id,
  album,
  album_id,
  album_artist,
  genre,
  year,
  track_number,
  disc_number,
  duration_seconds,
  bitrate,
  file_size,
  path,
  content_type,
  suffix,
  created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(navidrome_id) DO UPDATE SET
  title = excluded.title,
  artist = excluded.artist,
  artist_id = excluded.artist_id,
  album = excluded.album,
  album_id = excluded.album_id,
  album_artist = excluded.album_artist,
  genre = excluded.genre,
  year = excluded.year,
  track_number = excluded.track_number,
  disc_number = excluded.disc_number,
  duration_seconds = excluded.duration_seconds,
  bitrate = excluded.bitrate,
  file_size = excluded.file_size,
  path = excluded.path,
  content_type = excluded.content_type,
  suffix = excluded.suffix,
  created_at = excluded.created_at
`

type UpsertTrackParams struct {
	NavidromeID     string         `json:"navidrome_id"`
	Title           string         `json:"title"`
	Artist          string         `json:"artist"`
	ArtistID        sql.NullString `json:"artist_id"`
	Album           string         `json:"album"`
	AlbumID         sql.NullString `json:"album_id"`
	AlbumArtist     sql.NullString `json:"album_artist"`
	Genre           sql.NullString `json:"genre"`
	Year            sql.NullInt64  `json:"year"`
	TrackNumber     sql.NullInt64  `json:"track_number"`
	DiscNumber      sql.NullInt64  `json:"disc_number"`
	DurationSeconds int64          `json:"duration_seconds"`
	Bitrate         sql.NullInt64  `json:"bitrate"`
	FileSize        sql.NullInt64  `json:"file_size"`
	Path            string         `json:"path"`
	ContentType     sql.NullString `json:"content_type"`
	Suffix          string         `json:"suffix"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.NavidromeID,
		arg.Title,
		arg.Artist,
		arg.ArtistID,
		arg.Album,
		arg.AlbumID,
		arg.AlbumArtist,
		arg.Genre,
		arg.Year,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.DurationSeconds,
		arg.Bitrate,
		arg.FileSize,
		arg.Path,
		arg.ContentType,
		arg.Suffix,
		arg.CreatedAt,
	)
	return err
}

const upsertTrackAudioFeatures = `-- name: UpsertTrackAudioFeatures :exec
INSERT INTO track_audio_features (
  track_id,
  analyzed_at,
  file_duration_seconds,
  measured_integrated_lufs,
  measured_true_peak,
  replaygain_track_gain_db,
  replaygain_track_peak,
  replaygain_album_gain_db,
  replaygain_album_peak,
  effective_gain_db,
  effective_peak,
  effective_gain_source,
  effective_peak_source
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  analyzed_at = excluded.analyzed_at,
  file_duration_seconds = excluded.file_duration_seconds,
  measured_integrated_lufs = excluded.measured_integrated_lufs,
  measured_true_peak = excluded.measured_true_peak,
  replaygain_track_gain_db = excluded.replaygain_track_gain_db,
  replaygain_track_peak = excluded.replaygain_track_peak,
  replaygain_album_gain_db = excluded.replaygain_album_gain_db,
  replaygain_album_peak = excluded.replaygain_album_peak,
  effective_gain_db = excluded.effective_gain_db,
  effective_peak = excluded.effective_peak,
  effective_gain_source = excluded.effective_gain_source,
  effective_peak_source = excluded.effective_peak_source
`

type UpsertTrackAudioFeaturesParams struct {
	TrackID                int64           `json:"track_id"`
	AnalyzedAt             string          `json:"analyzed_at"`
	FileDurationSeconds    float64         `json:"file_duration_seconds"`
	MeasuredIntegratedLufs sql.NullFloat64 `json:"measured_integrated_lufs"`
	MeasuredTruePeak       sql.NullFloat64 `json:"measured_true_peak"`
	ReplaygainTrackGainDb  sql.NullFloat64 `json:"replaygain_track_gain_db"`
	ReplaygainTrackPeak    sql.NullFloat64 `json:"replaygain_track_peak"`
	ReplaygainAlbumGainDb  sql.NullFloat64 `json:"replaygain_album_gain_db"`
	ReplaygainAlbumPeak    sql.NullFloat64 `json:"replaygain_album_peak"`
	EffectiveGainDb        sql.NullFloat64 `json:"effective_gain_db"`
	EffectivePeak          sql.NullFloat64 `json:"effective_peak"`
	EffectiveGainSource    string          `json:"effective_gain_source"`
	EffectivePeakSource    string          `json:"effective_peak_source"`
}

func (q *Queries) UpsertTrackAudioFeatures(ctx context.Context, arg UpsertTrackAudioFeaturesParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackAudioFeatures,
		arg.TrackID,
		arg.AnalyzedAt,
		arg.FileDurationSeconds,
		arg.MeasuredIntegratedLufs,
		arg.MeasuredTruePeak,
		arg.ReplaygainTrackGainDb,
		arg.ReplaygainTrackPeak,
		arg.ReplaygainAlbumGainDb,
		arg.ReplaygainAlbumPeak,
		arg.EffectiveGainDb,
		arg.EffectivePeak,
		arg.EffectiveGainSource,
		arg.EffectivePeakSource,
	)
	return err
}

const upsertTrackSyncStatus = `-- name: UpsertTrackSyncStatus :exec
INSERT INTO navidrome_track_sync_status (
  track_id,
  navidrome_id,
  last_synced_at,
  sync_id
) VALUES (?, ?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  last_synced_at = excluded.last_synced_at,
  sync_id = excluded.sync_id
`

type UpsertTrackSyncStatusParams struct {
	TrackID      int64  `json:"track_id"`
	NavidromeID  string `json:"navidrome_id"`
	LastSyncedAt string `json:"last_synced_at"`
	SyncID       int64  `json:"sync_id"`
}

func (q *Queries) UpsertTrackSyncStatus(ctx context.Context, arg UpsertTrackSyncStatusParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackSyncStatus,
		arg.TrackID,
		arg.NavidromeID,
		arg.LastSyncedAt,
		arg.SyncID,
	)
	return err
}
